version: '3.8'
# Services is for all the containers that we will be creating
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    # Default Mongodb Port
      - "27017:27017"
    volumes:
    # Where the data will be stored
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

volumes:
  data: {}

networks:
  default:
    name: mongodb_network